### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/strip-css-comments#1]
It's already fast, but would be fun to optimize it further. Suggestions for perf tweaks welcome ;)

**Comment by Qix-** [comment]
Could port the whole thing to a C++ binding. :)

**Comment by sindresorhus** [comment]
If the native binding story in Node weren't completely horrifying, maybe yeah.

**Comment by floatdrop** [comment]
This regex gives 10,371 ops/sec vs 150 ops/sec with #12 (but cuts comments in strings):

```js
/\/\*[^!][\s\S]*?\*\//g
```
