### ISSUE TITLE
Strip only certain comments

### ISSUE THREAD

**Issue by Cleecanth** [sindresorhus/strip-css-comments#10]
It would be really useful to flag certain comments as strippable (basically the inverse of important comments). Either through a regex argument or a simple string.

For instance, comments that start with `/* $` or something.

Keep up the great work.

**Comment by sindresorhus** [comment]
Why? What's the use-case?

**Comment by Cleecanth** [comment]
Maybe this is just way too specific to my (and my team's) needs, but here's our particular use-case:
We have block-level comments in our `scss` files that work as a way to generate a style guide. The problem comes when we process our SCSS to CSS: It leaves us with a crazy number of comments (more or less randomly strewn throughout because of mixins and extends).

Obviously this is a non-issue when we compress our CSS, but during development, it's pretty annoying.

If we could flag our style-guide specific comments and strip them out during development, it'd be very helpful.

I'm sure this could be generalized to something else, but coming up with a hypothetical felt a little pointless. 

This is your tool, though, so feel free to assess as you see fit.

**Comment by sindresorhus** [comment]
I'd be open to a good PR with tests/docs that adds support for a `filter` option which is a function that get's the comment contents and returns a boolean whether to strip the comment. This would enable any kind of use-case, not just yours.

```js
stripCssComments(css, {
  filter: function (comment) {
   return /^##styleguide##/.test(comment);
  }
});
