### ISSUE TITLE
Add `whitespace` option

### ISSUE THREAD

**Issue by andrey-semenoff** [sindresorhus/strip-css-comments#14]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/strip-css-comments/issues/14)

Hallo!
Your plugin works good, but there is one annoying fact - after removing comment block it left empty line, and it looks not very tidily.
I propose to add some options to plugin to have a choice (like in gulp-strip-comments):
- **options.space** ⇒ Boolean
  false (default) - remove comment blocks entirely
  true - replace comment blocks with white spaces where needed, in order to preserve the original line + column position of every code element.
  NOTE: When this option is enabled, option trim is ignored.
- **options.trim** ⇒ Boolean
  false (default) - do not trim comments
  true - remove empty lines that follow removed full-line comments
  NOTE: This option has no effect when option space is enabled.

or at least add only first one.

Thanks.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/strip-css-comments/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
Yes, that sounds like a bug.

Why would you need to preserve the line/column in CSS? It makes sense in JS where you want stack traces to point to the correct source location, but you don't have that with CSS.

**Comment by andrey-semenoff** [comment]
I don't need to preserve lines - it'll be enough if it just don't left empty lines in CSS.
Here is CSS when plugin is off:
![strip-css-comments - off](https://cloud.githubusercontent.com/assets/16281097/15671416/6668e036-2733-11e6-84c5-c8ae1b1dbd72.png)

And here plugin is on:
![strip-css-comments - on](https://cloud.githubusercontent.com/assets/16281097/15671431/82299090-2733-11e6-84fa-5d12cf4ec4f8.png)

**Comment by sindresorhus** [comment]
Alright. I added a failing test for this, but I don't have time to fix this right now, so PR welcome :)

**Comment by andrey-semenoff** [comment]
Thank you. I'll try if I could :))

**Comment by lebbe** [comment]
"Why would you need to preserve the line/column in CSS? It makes sense in JS where you want stack traces to point to the correct source location, but you don't have that with CSS."

The developer tools in chrome use the sourcemap for pointing to file and line-number. This gets all wrong  if comment-stripping remove lines. I tend to do css-editing in the browser devtools, and paste the result into the correct file, so this is actually a feature I would want.

**Comment by sindresorhus** [comment]
I think it would make sense to implement a `whitespace` option, like https://github.com/sindresorhus/strip-json-comments#whitespace

**Comment by poisxpto** [comment]
Hi,
I am new to this, so keep that in mind.

Something like this:

_create a var after the one "preserveImportant"_
var keepWhitespaces = opts.whitespace || true;

_and when you return the result, do it like this:_
if (keepWhitespaces == true) {
return ret.replace(/^\s*\n/gm, "");
}
else return ret;

run the code in the console and try it.
[strip-css-comments.js.zip](https://github.com/sindresorhus/strip-css-comments/files/793869/strip-css-comments.js.zip)

**Comment by sindresorhus** [comment]
For anyone that wants to work on this, see https://github.com/sindresorhus/strip-css-comments/pull/18 for an initial attempt.

**Comment by brainlulz** [comment]
Hey, frontend developer here, may I work on this issue ? Would of course add a test, documentation and update the TS definitions :)

**Comment by brainlulz** [comment]
Currently working on this. Will integrate the current PR #19 in it. The option will be a default option regarding the strip-json-comments implementation.
