### ISSUE TITLE
Add buffer support

### ISSUE THREAD

**Issue by terribleplan** [sindresorhus/strip-css-comments#3]
It would be nice if buffers were natively supported to enable the following pattern:

```js
var fs = require('fs'),
    stripCssComments = require('strip-css-comments');

fs.readFile('./file.css', function(err,buf){
    console.log(stripCssComments(buf));
});
```
which is quite natural to use in node.

Worst case you could just turn buffers to strings with `.toString()`

**Comment by sindresorhus** [comment]
Alright, so turns out buffers are actually slower than strings for this in latest Node.

See https://github.com/sindresorhus/strip-css-comments/issues/9

So going with just converting the Buffer to a string for now...
