### ISSUE TITLE
Streaming interface

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/strip-css-comments#5]
Could be useful as a Transform stream.

**Comment by lydell** [comment]
I felt like learning a bit about streams and buffers today, so I played with making a streaming program that strips _singleline_ comments from CSS. I thought you might be interested—perhaps it can be used as inspiration :) [strip-css-singleline-comments](https://github.com/lydell/strip-css-singleline-comments)

**Comment by lydell** [comment]
(I’ve added a sync interface as well to my module now.)

**Comment by sindresorhus** [comment]
@lydell Interesting! That's very close to how I imagined doing it :)

**Comment by stevemao** [comment]
Any news here?
